/********************************************************************
* BlueDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BlueDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBlueDict();
extern void G__cpp_setup_inheritanceBlueDict();
extern void G__cpp_setup_typetableBlueDict();
extern void G__cpp_setup_memvarBlueDict();
extern void G__cpp_setup_globalBlueDict();
extern void G__cpp_setup_memfuncBlueDict();
extern void G__cpp_setup_funcBlueDict();
extern void G__set_cpp_environmentBlueDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Blue.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BlueDictLN_TClass;
extern G__linked_taginfo G__BlueDictLN_TBuffer;
extern G__linked_taginfo G__BlueDictLN_TMemberInspector;
extern G__linked_taginfo G__BlueDictLN_TObject;
extern G__linked_taginfo G__BlueDictLN_TString;
extern G__linked_taginfo G__BlueDictLN_ROOT;
extern G__linked_taginfo G__BlueDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BlueDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BlueDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BlueDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BlueDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__BlueDictLN_TLatex;
extern G__linked_taginfo G__BlueDictLN_TDatime;
extern G__linked_taginfo G__BlueDictLN_ROOTcLcLMath;
extern G__linked_taginfo G__BlueDictLN_ROOTcLcLMathcLcLGSLRandomEngine;
extern G__linked_taginfo G__BlueDictLN_Blue;

/* STUB derived class for protected member access */
