#!/bin/ksh
#
# Compile all B_*cxx functions in current directory (Richard.Nisius@mpp.mpg.de)
#
################################################################################
#
#-- Find all input files
#
#dir=`dirname $0`

set `ls B_*cxx`
echo "... CompAll: I use this list: $*"

############################################################
#
#-- Run all combinations
#
for i
do
    echo "... CompAll: ./CompOne $i"
                       ./CompOne $i
done

